[graph]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[advisories]
version = 2
yanked = "deny"

[bans]
multiple-versions = "allow"
wildcards = "allow"

[licenses]
version = 2
confidence-threshold = 1.0
allow = ["Apache-2.0", "GPL-3.0", "MIT", "MPL-2.0"]
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
