[package]
name = "parser"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
elaboration.path = "../elaboration"

derive_more.workspace = true
pest.workspace = true
pest_derive.workspace = true
